### ISSUE TITLE
Feature Request: Preserve tag syntax

### ISSUE THREAD

**Issue by Aaron-Bopp** [chrisgrieser/obsidian-smarter-md-hotkeys#13]
### Feature Requested

This is similar to what I suggested for links in the other issue, but for tags

When a cursor is in a tag, place syntax around the tag instead of around the word
This 
![image](https://user-images.githubusercontent.com/48270139/148858640-6846f70f-a7c2-40c4-ad5f-f1ae482a2505.png)
turns into this 
![image](https://user-images.githubusercontent.com/48270139/148858791-10caeb98-6727-4b1a-a10c-5743661cb6cb.png) 
instead of this 
![image](https://user-images.githubusercontent.com/48270139/148859562-1da5c13c-4908-4cd6-bf79-729d8516d4e7.png)

I think this would make sense for the other commands as well.

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I have checked that there isn't [another hotkey plugin](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.01+Plugins+by+Category/Plugins+that+add+or+manage+hotkeys) that does what I want.
- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
that one is a good idea; fixed with latest release.

Also, I changed some stuff that you can see exactly which syntax is excluded or included in the markup, in case you want to take a look (or fix simpler stuff with a PR, if you have another idea) https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys/blob/master/const.ts#L115
