### ISSUE TITLE
Feature Request: Better support for sub-items and sub-tasks

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#3]
As an addition to https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys/issues/1, it seems it does not work well for sub-items or sub-tasks. For instance, the following effect would be applied if the line for Item B is selected:
```
- Item A
==    - Item B==
```
While the desired effect would be:
```
- Item A
    - ==Item B==
```

Also, when the selection is across both the parent and child items, maybe it would be great if the hotkeys can be applied to the entire lines of the parent and child items. The current effect is as follows:
<img width="254" alt="Screenshot 2021-11-20 at 19 32 07" src="https://user-images.githubusercontent.com/44930227/142737417-c8fc5c78-3c6e-4e32-9f41-53cf918d0749.png">
Or
<img width="290" alt="Screenshot 2021-11-20 at 19 37 34" src="https://user-images.githubusercontent.com/44930227/142737517-37b36b77-eecc-4780-85dc-2cc093ab91bb.png">

The desired effect would be:
<img width="300" alt="Screenshot 2021-11-20 at 19 37 52" src="https://user-images.githubusercontent.com/44930227/142737520-aa07c378-d431-4fd7-bcd7-c5b4787a232a.png">

**Comment by chrisgrieser** [comment]
First part should be fixed now, the second part will take a bit of time though

**Comment by chrisgrieser** [comment]
Okay, this was the most complicated coding I have ever done in my life, but release 0.12 should now work properly on multiline.

Give it a try whether your task-related use cases work with this :)

![Screen Recording 2021-12-07 at 01 14 40](https://user-images.githubusercontent.com/73286100/144943016-b998edd7-f859-4a1f-91b1-4883a2322841.gif)

**Comment by wenlzhang** [comment]
> Okay, this was the most complicated coding I have ever done in my life

Thanks for the efforts on this!

A minor issue is that it would be great if the hotkeys can be applied to the entire lines of the first and last lines, although one may not select the first word of the first line and the last word of the last line, e.g. in the case of long lines. The reason for this is that one may would like to apply this to all selected lines since the selection is across multiple lines. Of course, if this takes a lot of efforts to implement, then this can be neglected. :-)

![CleanShot 2021-12-07 at 08 59 20](https://user-images.githubusercontent.com/44930227/144989644-2504d389-716c-4bcd-b559-0f25ba196e13.gif)

**Comment by chrisgrieser** [comment]
Yeah, it was actually a very fun challenge and I learned a lot implementing this :)

Concerning your suggestion, the idea is cool interesting, but I am unsure how I feel about that, because there are also cases where want to *not* apply the markup to the whole line, for example here:

```md
- This is **stone**.
- **Stone** is an important material.
```

Implementing expand to the whole line would remove the ability to make markup like in this example; while the current expansions to whole words would leave both options available to the user. So I am inclined to keep the current implementation.

**Comment by wenlzhang** [comment]
> Implementing expand to the whole line would remove the ability to make markup like in this example; while the current expansions to whole words would leave both options available to the user.

Indeed. I understand and agree with this. :-)

**Comment by chrisgrieser** [comment]
great I'll close this then. :)

btw, just so you as the currently most active user know: I added [a small roadmap](https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys#roadmap) to the Readme :)

**Comment by chrisgrieser** [comment]
btw, I had an idea: expanding to the whole line makes sense, when you have *at least 3 lines* selected, because it is very implausible that you want to markup a word, a line, and then a word again. 

So I could add a check whether at least 3 lines are selected and in that case expand to the whole line! 🙂 

I added that idea to the [roadmap](https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys#roadmap)

**Comment by wenlzhang** [comment]
> So I could add a check whether at least 3 lines are selected and in that case expand to the whole line! 🙂

Looking forward to this! 😀
