### ISSUE TITLE
Feature Request: Better for inline code block

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#6]
**Feature Requested**
It would be great if inline block can be better supported.

**Relevant Screenshots**
The current effect can be seen as follows:
![CleanShot 2021-11-23 at 18 44 56](https://user-images.githubusercontent.com/44930227/143077185-700f262e-0b7d-4b74-ae51-3b6374a0724e.gif)

**Comment by chrisgrieser** [comment]
that's a very smart idea, I like it! in version 0.9.10, I just implemented exactly that. As opposed to all other commands, the command for inline does not apply the markup at word boundaries but rather at the spaces before and after the cursor position. 🎉

**Comment by wenlzhang** [comment]
Would it be possible to also support inline code block with brackets, e.g. `dv.fileLink(path, [embed?], [display-name])`?

For this to work, it may need to check the pair of different types of brackets included in the code block.

**Comment by chrisgrieser** [comment]
Brackets are indirectly supported, the rule I applied is simply that the selection is extended to the preceding and following space. So when you write `dv.fileLink(path,[embed?],[display-name])` it will work.

I am hesitating to implement something more precise that properly considers brackets since there is much, much more ambiguity. Especially considering that other people might want to markup code from many different languages, each having specific bracketing rules. 

So *to get it right*, would take a lot of effort, with a relatively minor benefit. So at least for now, I don't think it's worth the effort going beyond the current implementation.

**Comment by wenlzhang** [comment]
I understand. Thanks for the detailed explanations!
