### ISSUE TITLE
[BUG] All hotkeys stopped working

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#7]
As can be seen from the GIF below, everything stopped working for me with Obsidian v0.13.8 and this plugin of version 0.13.0.

![](https://user-images.githubusercontent.com/44930227/145709094-d89da974-5359-4cfd-b6a9-6d21f149f528.gif)

**Comment by chrisgrieser** [comment]
Hmmm, my suspicion is that this is related to the new Insider Release, since it uses a different version of CodeMirror. Could you confirm the following:

- Try using `smarter inline code`. This one works independent from the CodeMirror version, so if inline code works, the new CodeMirror version is the problem.
- Similarly, you could try to use the Legacy Editor in the the Obsidian settings and see if it works then.

**Comment by wenlzhang** [comment]
Indeed, both the `smarter inline code` and Legacy Editor work for me.

**Comment by chrisgrieser** [comment]
ugh, then this is some issue with the new CodeMirror Version. I'll try to find out what's the issue here :(

**Comment by chrisgrieser** [comment]
Okay, I tried something. Could you update to 0.13.2 and try whether it works now?

**Comment by wenlzhang** [comment]
Thanks for the update! However, it does not work for me. I got similar errors as in the last version.

**Comment by chrisgrieser** [comment]
Okay, I probably found the issue, should be fixed now

**Comment by wenlzhang** [comment]
Great! It works for some cases. However, I got the following error when selecting the entire line with triple-clicking:

<img width="564" alt="Screenshot 2021-12-12 at 18 40 30" src="https://user-images.githubusercontent.com/44930227/145723272-d773defe-2933-4df9-a521-ed0c183a4c2f.png">

**Comment by chrisgrieser** [comment]
okay, found the issue, latest release should fix it

**Comment by wenlzhang** [comment]
Great! It works now.
