### ISSUE TITLE
Feature Request: Support selectively adding commands to right-click menu items

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/obsidian-smarter-md-hotkeys#9]
It can be very convenient if some commands can be added as right-click menu items. One may not add all of the commands, so it would be great if one can configure this in the plugin configuration pane.

**Comment by chrisgrieser** [comment]
I was actually looking into how to implement this, but then I stumbled upon this plugin which already seems to do exactly that what you want.

[kzhovn/obsidian-customizable-menu](https://github.com/kzhovn/obsidian-customizable-menu)

Since there is probably no point in replicating a feature already offered by I'll close this one.
